GET https://obscure-woodland-13477.herokuapp.com/api/v1/flower

###
POST https://obscure-woodland-13477.herokuapp.com/api/v1/flower
Content-Type: application/json

{
  "color": 0,
  "description": "chamomile",
  "flowerType": 0,
  "price": 10,
  "sepalLenght": 30
}